#!/bin/bash

printf "Normal\n"
printf "\033[1mBold\033[22m\n"
printf "\033[3mItalic\033[23m\n"
printf "\033[3;1mBold Italic\033[0m\n"
printf "\033[4mUnderline\033[24m\n"
printf "\nLigatures (font should fuse each into one glyph):\n"
printf "  equality          ==\n"
printf "  strict equality   ===\n"
printf "  not equal         !==\n"
printf "  greater-or-equal  >=\n"
printf "  less-or-equal     <=\n"
printf "  fat arrow         =>\n"
printf "\nWide glyphs (CJK, must occupy 2 cells):\n"
printf "  U+F909 CJK COMPAT IDEOGRAPH  契\n"
printf "  U+F952 CJK COMPAT IDEOGRAPH  勒\n"
printf "  U+F9B1 CJK COMPAT IDEOGRAPH  鈴\n"
printf "\nNerd Font icons (private use; need a patched font):\n"
printf "  U+F0C5 files                 \n"
printf "  U+F15B file                  \n"
printf "  U+F608 folder                \n"
printf "  U+F022 list                  \n"
printf "  U+F423 gear                  \n"
printf "  U+F426 tag                   \n"

printf "\nText symbols (must be solid glyphs, NOT tofu boxes):\n"
printf "  U+2731 HEAVY ASTERISK        ✱\n"
printf "  U+2732 OPEN CENTRE ASTERISK  ✲\n"
printf "  U+270E LOWER RIGHT PENCIL    ✎\n"
printf "  U+2713 CHECK MARK            ✓\n"
printf "  U+2743 HEAVY TEARDROP ASTER  ❃\n"
printf "  U+2761 CURVED STEM PARAGRAPH ❡\n"

printf "\nDefault-text emoji (monochrome bare; color only with VS16 U+FE0F):\n"
printf "  U+2733 EIGHT SPOKED ASTERISK bare ✳   vs16 ✳️\n"
printf "  U+2744 SNOWFLAKE             bare ❄   vs16 ❄️\n"
printf "  U+2764 HEAVY BLACK HEART     bare ❤   vs16 ❤️\n"
printf "  U+2600 SUN                   bare ☀   vs16 ☀️\n"

printf "\nEmoji (default emoji presentation; always color):\n"
printf "  U+2728 SPARKLES              ✨\n"
printf "  U+2705 CHECK MARK BUTTON     ✅\n"
printf "  U+274C CROSS MARK            ❌\n"
printf "  U+26BD SOCCER BALL           ⚽\n"
printf "  U+1F600 GRINNING FACE        😀\n"
printf "  U+1F680 ROCKET               🚀\n"
