//go:build ignore

// Command gen_eaw generates eaw_wide.go from the vendored Unicode East Asian
// Width data file (term/ucd/EastAsianWidth.txt). It emits the set of code-point
// ranges whose East_Asian_Width property is Wide (W) or Fullwidth (F) — the
// characters wcwidth counts as two cells.
//
// go-term uses this as an up-to-date override on top of rivo/uniseg, whose
// bundled width data is frozen at Unicode 15.0.0. Consulting a current table
// lets go-term's wide/narrow decision track jquast's python-wcwidth (the oracle
// ucs-detect measures against). uniseg still owns grapheme segmentation and the
// zero-width decision; this table only ever upgrades a width-1 rune to 2.
//
// Regeneration:
//
//	go generate ./term
//
// To retarget a newer Unicode version, replace term/ucd/EastAsianWidth.txt with
// the matching release and re-run.
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	ucdPath = "ucd/EastAsianWidth.txt"
	outPath = "eaw_wide.go"
)

type rng struct{ lo, hi rune }

func main() {
	ranges, version, err := parse(ucdPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen_eaw:", err)
		os.Exit(1)
	}
	if err := emit(outPath, ranges, version); err != nil {
		fmt.Fprintln(os.Stderr, "gen_eaw:", err)
		os.Exit(1)
	}
	fmt.Printf("gen_eaw: wrote %d ranges (Unicode %s) to %s\n", len(ranges), version, outPath)
}

// parse reads EastAsianWidth.txt and returns the sorted, coalesced set of Wide
// and Fullwidth code-point ranges plus the file's Unicode version string.
func parse(path string) (ranges []rng, version string, err error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, "", err
	}
	defer f.Close()

	var raw []rng
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		// Version lives in the header, e.g. "# EastAsianWidth-17.0.0.txt".
		if version == "" && strings.HasPrefix(line, "# EastAsianWidth-") {
			version = strings.TrimSuffix(strings.TrimPrefix(line, "# EastAsianWidth-"), ".txt")
			continue
		}
		if i := strings.IndexByte(line, '#'); i >= 0 {
			line = line[:i] // strip trailing comment
		}
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// "4DC0..4DFF     ; W" or "0020 ; Na". Field 0 is the code-point span,
		// field 1 the property. Match W/F exactly (not Na, A, H, N).
		semi := strings.IndexByte(line, ';')
		if semi < 0 {
			continue
		}
		prop := strings.TrimSpace(line[semi+1:])
		if prop != "W" && prop != "F" {
			continue
		}
		span := strings.TrimSpace(line[:semi])
		lo, hi, perr := parseSpan(span)
		if perr != nil {
			return nil, "", fmt.Errorf("bad span %q: %w", span, perr)
		}
		raw = append(raw, rng{lo, hi})
	}
	if err := sc.Err(); err != nil {
		return nil, "", err
	}

	sort.Slice(raw, func(i, j int) bool { return raw[i].lo < raw[j].lo })

	// Coalesce adjacent/overlapping ranges so the binary search scans fewer
	// entries (e.g. the reserved gaps inside CJK Extension B are also Wide).
	for _, r := range raw {
		if n := len(ranges); n > 0 && r.lo <= ranges[n-1].hi+1 {
			if r.hi > ranges[n-1].hi {
				ranges[n-1].hi = r.hi
			}
			continue
		}
		ranges = append(ranges, r)
	}
	return ranges, version, nil
}

// parseSpan parses "XXXX" or "XXXX..YYYY" hex code-point spans.
func parseSpan(s string) (lo, hi rune, err error) {
	a, b, found := strings.Cut(s, "..")
	l, err := strconv.ParseInt(a, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	if !found {
		return rune(l), rune(l), nil
	}
	h, err := strconv.ParseInt(b, 16, 32)
	if err != nil {
		return 0, 0, err
	}
	return rune(l), rune(h), nil
}

func emit(path string, ranges []rng, version string) error {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen_eaw.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: Unicode %s EastAsianWidth.txt (Wide + Fullwidth).\n\n", version)
	b.WriteString("package term\n\n")
	b.WriteString("// eawWideRanges is the sorted, coalesced set of code-point ranges with\n")
	b.WriteString("// East_Asian_Width Wide or Fullwidth. Searched by eawWide (grid.go).\n")
	b.WriteString("var eawWideRanges = [...]struct{ lo, hi rune }{\n")
	for _, r := range ranges {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", r.lo, r.hi)
	}
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
