//go:build ignore

// Command gen_kgpdiacritics generates kgp_diacritics.go from kitty's vendored
// row/column diacritic list (term/ucd/rowcolumn-diacritics.txt).
//
// The Kitty Graphics Protocol encodes the row and column of a Unicode
// placeholder cell as combining characters appended to U+10EEEE. The value a
// diacritic stands for is its *position* in that file — line 0 is 0, line 1 is
// 1, and so on — so the table has to be reproduced exactly, in file order.
// It is frozen upstream (derived from Unicode 6.0.0) and will not grow: the
// protocol's row/column range is whatever these 297 entries cover.
//
// The emitted table is sorted by code point so lookups can binary-search
// (the source file is very nearly in that order already); the value is carried
// alongside each rune rather than implied by the index, which keeps the
// generator honest if upstream ever reorders the file.
//
// Regeneration:
//
//	go generate ./term
//
// Source: https://github.com/kovidgoyal/kitty/blob/master/gen/rowcolumn-diacritics.txt
package main

import (
	"bufio"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

const (
	diacriticsPath = "ucd/rowcolumn-diacritics.txt"
	diacriticsOut  = "kgp_diacritics.go"
)

type diacritic struct {
	r   rune
	val int
}

func main() {
	list, err := parseDiacritics(diacriticsPath)
	if err != nil {
		fmt.Fprintln(os.Stderr, "gen_kgpdiacritics:", err)
		os.Exit(1)
	}
	if err := emitDiacritics(diacriticsOut, list); err != nil {
		fmt.Fprintln(os.Stderr, "gen_kgpdiacritics:", err)
		os.Exit(1)
	}
	fmt.Printf("gen_kgpdiacritics: wrote %d diacritics to %s\n",
		len(list), diacriticsOut)
}

// parseDiacritics reads the UnicodeData-shaped list and pairs each code point
// with its line index — the number that code point encodes.
func parseDiacritics(path string) ([]diacritic, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var list []diacritic
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// "0305;COMBINING OVERLINE;Mn;230;NSM;;;;;N;…" — only field 0 matters.
		field := line
		if semi := strings.IndexByte(line, ';'); semi >= 0 {
			field = line[:semi]
		}
		cp, err := strconv.ParseInt(field, 16, 32)
		if err != nil {
			return nil, fmt.Errorf("bad code point %q: %w", field, err)
		}
		list = append(list, diacritic{r: rune(cp), val: len(list)})
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	if len(list) == 0 {
		return nil, fmt.Errorf("%s: no diacritics found", path)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].r < list[j].r })
	for i := 1; i < len(list); i++ {
		if list[i].r == list[i-1].r {
			return nil, fmt.Errorf("duplicate code point U+%04X", list[i].r)
		}
	}
	return list, nil
}

func emitDiacritics(path string, list []diacritic) error {
	var b strings.Builder
	b.WriteString("// Code generated by gen_kgpdiacritics.go; DO NOT EDIT.\n")
	b.WriteString("// Source: kitty gen/rowcolumn-diacritics.txt (Unicode 6.0.0 derived).\n\n")
	b.WriteString("package term\n\n")
	b.WriteString("// kgpDiacritics maps the combining characters the Kitty Graphics Protocol\n")
	b.WriteString("// uses for Unicode-placeholder row/column encoding to the number each one\n")
	b.WriteString("// stands for. Sorted by code point; searched by kgpDiacriticValue.\n")
	fmt.Fprintf(&b, "var kgpDiacritics = [%d]struct {\n\tr   rune\n\tval uint16\n}{\n", len(list))
	for _, d := range list {
		fmt.Fprintf(&b, "\t{0x%04X, %d},\n", d.r, d.val)
	}
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
